### ISSUE TITLE
[LNbank] Cannot receive

### ISSUE THREAD

**Issue by jaonoctus** [btcpayserver/btcpayserver-plugins#10]
Related to #6, there is some issues still.

- [ ] I cannot create invoices from `lnbank > wallet > receive` if the description field is empty;
- [ ] I cannot create invoices from a store connected to the lnbank wallet. 
`NodeInfo failed to be fetched: The lightning node did not reply in a timely manner`

**Comment by jaonoctus** [comment]
cc @dennisreimann

**Comment by jaonoctus** [comment]
- @dennisreimann Is the #14 PR will also fix the second issue?

> I cannot create invoices from a store connected to the lnbank wallet.
> NodeInfo failed to be fetched: The lightning node did not reply in a timely manner

**Comment by dennisreimann** [comment]
We'll have to see. There's not much I can do about it in LNbank – there's certainly the overhead of connecting to the node via API, but that needs to be done. I'll see if I can optimize other things if the problem still exists.

**Comment by jaonoctus** [comment]
@dennisreimann I see. Anyways, thank you so much for the effort ❤️

**Comment by dennisreimann** [comment]
We'll keep pushing till it works :)
