### ISSUE TITLE
`LN BANK` [UX] - When requesting a payment, LNBank redirects to store dashboard

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-plugins#15]
When you create a payment request with LNBANK it instantly redirects to store's dashboard, which was a weird UX, instead I should be able to see the QR code right away.

BTCPAy: `v1.4.7.0`
LNBANK:  `1.1.0.0`
Lightning implemetation: c-lightning
Logs: none
Don't have any other plguins enabled except for system defaults.

**Comment by dennisreimann** [comment]
Yes, fixed in the upcoming version. Will send it soon :)

**Comment by dennisreimann** [comment]
Fixed with #17.
