### ISSUE TITLE
[`LNBank Plugin`] Cannot send funds

### ISSUE THREAD

**Issue by jaonoctus** [btcpayserver/btcpayserver-plugins#16]
**Description**
I cannot pay invoices with a LNBank wallet.

**Steps to reproduce the reported bug**

1. Go to 'LNBank' plugin;
2. Click on any wallet that have funds;
3. Click on 'pay';
4. Paste the invoice;
5. Click on 'Decode payment request';
6. Click on 'Send N funds';
7. See error.

![image](https://user-images.githubusercontent.com/7918067/157159096-a3e1bd8f-ad82-471c-a532-ca0d1bfcc827.png)

**BTCPay Environment:**
- BTCPay Server Version: `v1.4.7.0`
- Deployment Method: `Docker` 
- Lightning: `LND`
- Browser: `Chrome`

**Logs**

```
Method not found: 'System.Threading.Tasks.Task BTCPayServer.Client.BTCPayServerClient.PayLightningInvoice(System.String, BTCPayServer.Client.Models.PayLightningInvoiceRequest, System.Threading.CancellationToken)'.
```

**Comment by dennisreimann** [comment]
This looks like there's a version mismatch. Does upgrading to LNbank v1.1.1 solve it?

**Comment by jaonoctus** [comment]
Yes! Didn't noticed that. Bumped LNBank to `1.1.1.0`

![image](https://user-images.githubusercontent.com/7918067/157497746-ba59b4b9-bfd1-41a6-ab7f-81c27fc4397a.png)
