### ISSUE TITLE
Enabled FixedFloat shows as disabled on integrations page

### ISSUE THREAD

**Issue by BitcoinMitchell** [btcpayserver/btcpayserver-plugins#18]
I have FixedFloat enabled in my store (and can see it working in the invoice page), but it still shows as disabled in the overview page:

| **Configuration** |  **Invoice** |
|---|---|
| ![image](https://user-images.githubusercontent.com/27309467/159185956-99c87a15-6eb1-435c-8c3c-7149a3c5f100.png) | ![image](https://user-images.githubusercontent.com/27309467/159185844-56302edf-f75d-4453-903e-ba8356131a97.png) |
 

| **Integration page** |
|---|
| ![image](https://user-images.githubusercontent.com/27309467/159185802-a48a175e-5931-446b-a4f1-8fcbd2c7fc17.png) |

**Comment by Kukks** [comment]
I think i fixed it with latest release 👍
