### ISSUE TITLE
Cannot install Liquid+ on BTCPayServer 1.2.4.0

### ISSUE THREAD

**Issue by JamesAEGray** [btcpayserver/btcpayserver-plugins#2]
I am running 1.2.4.0, but it says I need greater than 1.2.4.0. But am I mistaken or is 1.2.4.0 is the latest?

I’m not entirely sure, as this program is out of my wheelhouse, however there is a line which stipulates the following in the GitHub repository:

"Condition":"\u003E1.2.4.0"

Given that \u003E is “greater than” and not “greater than or equal to” could that be causing the issue?

**Comment by Kukks** [comment]
It was meant so that it becomes available in a future version. I've updated the plugin system so that we can have multiple versions of the same plugin available in this repository for different btcpayserver versions.
