### ISSUE TITLE
LNURL-Withdraw for LNbank accounts

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver-plugins#24]
As an easier alternative to Pull Payments I would like to offer my users LNURL-W for their account, so they can save it and pull without going to BTCPay.

The best experience will be when wallets and LNbank will support balance check and balance notify, so their wallet will see remote balance and offer pulling it.

The link and QR code could be on the Pay page.

**Comment by Kukks** [comment]
Slightly related : https://github.com/btcpayserver/btcpayserver/pull/3709

**Comment by dennisreimann** [comment]
Can you elaborate on the use case a bit? I can imagine the wallet owner generating a one-time withdraw transaction, instead of directly paying an invoice­, but that doesn't seem to be what you are looking for.

**Comment by iBobik** [comment]
It is useful for permanent LNURL what the owner can save and use regularly to withdraw funds. 

Especially useful with balaceCheck and balanceNotify, so his wallet can see amount and offer pull on one click.

Honza Pobořil
💬Signal

**Comment by dennisreimann** [comment]
Providing a general LNURL-Withdraw code for LNbank wallets would be very risky, because that would allow for draining the wallet. I can see at least two cases which would be good though:

- The wallet owner generates a transaction that can be redeemed using LNURL-W, so that the amount is predefined. (similar to pull payments)
- General LNURL-W access, but with some additional authentication/authorization conditions, so that only certain users are allowed to access it.

**Comment by dennisreimann** [comment]
Tracking the issue in dennisreimann/btcpayserver-plugin-lnbank#18.

**Comment by iBobik** [comment]
LNbits has permanent withdraw code without any additional authorization, but I know it is not good example of secure product. :-)

Sadly the standard does not support authorization.

For my use case it could be useful to offer code valid for e.g. minute, so it will require user to login first and then use code in the UI.

But this will not be compatible with balanceCheck and balanceNotify flow. Wallets does not support it today, so it will not be pain to not implement it now, but in the future wallets can implement it. Having permanent code saved from BTCPay directly to the wallet is not bad, we just need to warm users to not save it insecurely somewhere else. Maybe situation could be improved by some constrain checking that the wallet checked balance in e.g. one minute after code generation, so the server knows it was probably saved to the wallet and can change code's validity to e.g. one year.

Also in the most cases user want to pull all amount, so requiring to write amout is complication.

Honza Pobořil
💬Signal
