### ISSUE TITLE
LNbank can not transfer between accounts on one node

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver-plugins#25]
When tried to transfer money from one LNbank account to another LNbank account it fails on LND's restriction.

It could be acomplished by option allow_self_payment when paying invoice.

LNbank could also do it just in it's database, but this will not allow to send e.g. to LNbits using the same LND.

**Comment by dennisreimann** [comment]
We'll need a new Lightning lib (and hence BTCPay Server update) for this, but this will be fixed once btcpayserver/BTCPayServer.Lightning#71 is merged.
