### ISSUE TITLE
FixedFloat Affiliate program profiteering

### ISSUE THREAD

**Issue by bobget** [btcpayserver/btcpayserver-plugins#33]
We should have the option of inputing our own Fixed float affiliate reference code in the settings of the plugin instead of having the hard-coded one from whoever made the plugin. And he is racking in 40% of the profit from the fixed float exchanges as per their affiliate program.

EDIT: found the hardcoded ref in fixedFloatComponent.js

**Comment by pavlenex** [comment]
Duplicate #29
