### ISSUE TITLE
[Bug] Lost admin access to podcast (podserver)

### ISSUE THREAD

**Issue by johnongit** [btcpayserver/btcpayserver-plugins#49]
I've found an edge case where and admin can lose podcast admin role.

1. Create a new podcat
2. In "Editor" tab, add admin email as Editor

By doing this action, Admin role is erased.

-> The plugin should prevent this action

I've doing it on my btcpayserver and I've lost access to my podcast.

**Comment by dennisreimann** [comment]
Thanks for reporting! I just fixed this in v0.1.2
