### ISSUE TITLE
Lightning Node is unavailable when using LNBank Wallet

### ISSUE THREAD

**Issue by o3k1n** [btcpayserver/btcpayserver-plugins#50]
**What is your BTCPay version?**
BTCPayServer v1.6.11.0
LNbank v1.3.3.0

**How did you deploy BTCPay Server?**
Docker deploy on Digital Ocean

**What happened?**

Lightning Node is unavailable when using LNBank Wallet as connection.

The node is available when connection is set to internal node. 
After selecting LNbank wallet as Lightning connection, there is no error and the connection string seems legit.
When clicking "Test Connection" under tab "Use custom node" there is an error " The lightning node did not reply in a timely manner".

Switching back to Internal node makes the node available immediately again.

I could not find anything in the logs. Please let me know which logs I can supply.

**How did you encounter this bug?**

    Lightning
    Settings
    Change connection
    Use LNbank
    SAVE
    Use Custom Node
    Test Connection => Error
    Public Node Info => unavailable
    
    
<img width="791" alt="Screenshot 2022-09-29 at 16 55 17" src="https://user-images.githubusercontent.com/92563141/193066835-ccdccae8-8e4c-4fe0-af50-68acf6cf37d8.png">
<img width="786" alt="Screenshot 2022-09-29 at 16 55 02" src="https://user-images.githubusercontent.com/92563141/193066841-72b0f73d-4919-46f9-a1a1-30fb1db460f8.png">
<img width="274" alt="Screenshot 2022-09-29 at 16 54 13" src="https://user-images.githubusercontent.com/92563141/193066852-4477e668-e754-47bf-beac-ed009ec9d60d.png">

**Comment by dennisreimann** [comment]
What du you get when you run the following command in the shell? (Please replace `APIKEY` and `SERVER` with the values from the connection string)

`curl -v -H "Authorization: Bearer APIKEY" https://SERVER/plugins/lnbank/api/lightning/info`

Feel free to reach out to me on Mattermost, I already pinged you there.

**Comment by dennisreimann** [comment]
We tracked this down to a network/DNS problem on the server.
