### ISSUE TITLE
[bug] Invalid date in rss feed returned by PodServer

### ISSUE THREAD

**Issue by johnongit** [btcpayserver/btcpayserver-plugins#57]
The publication date in rss feed is currently uploaded date and not the real publication date.
https://btcpay.openchain.fr/plugins/podserver/podcast/lentonnoir-du-bitcoin/feed

**Comment by johnongit** [comment]
ping @dennisreimann I would love to fix this issue. My RSS feed is currently unreliable :(

**Comment by dennisreimann** [comment]
Sorry and thanks for the ping, it's now fixed in [v0.1.4](https://github.com/dennisreimann/btcpayserver/releases/tag/BTCPayServer.PodServer/v0.1.4).
